# Generated by Django 4.1.3 on 2022-11-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_user_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
